# Login http://localhost:8080/apex/apex_admin with following credential:
# username: ADMIN
# password: Oracle_11g

# hostname: localhost
# port: 49161
# sid: xe
# username: system
# password: oracle

FROM wnameless/oracle-xe-11g-r2:18.04-apex
ADD init.sql /docker-entrypoint-initdb.d/